version: '3.7'

services:
  pm.kusanagi.nginx:
    container_name: pm.kusanagi.nginx
    image: pressmaninc/pm-kusanagi-nginx:latest
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./kusanagi:/var/www/html/kusanagi
    links:
      - pm.kusanagi.php7:php
    ports:
      - "80:80"
      - "443:443"
    
  pm.kusanagi.php7:
    container_name: pm.kusanagi.php7
    image: pressmaninc/pm-kusanagi-php73:latest
    links:
      - pm.kusanagi.mariadb:mysql
    volumes:
      - ./etc/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./kusanagi:/var/www/html/kusanagi

  pm.kusanagi.mariadb:
    container_name: pm.kusanagi.mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
